theme: jekyll-theme-minimal
title: FOSS Sustainability
logo: /assets/img/lifesaver.png
description: Overview of FOSS/Open Source Sustainability and Pay The Maintainers movements.
show_downloads: false
google_analytics: G-TB6JSQWZ3Y

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary
social:
  name: Punderthings℠ LLC
  links:
    - http://punderthings.com/
    - http://shanecurcuru.org/

include:
  - _pages

collections:
  aspects:
    output: true
    permalink: /:collection/:path
  governance:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: "aspects"
    values:
      layout: "aspect"
  - scope:
      path: ""
      type: "governance"
    values:
      layout: "governance"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
